# =================================================================
# Dockerfile para Kafbat (antigo Kafka UI)
# =================================================================

# Define a imagem oficial do Kafbat como base. Usar a tag :latest
# garante que você está pegando a versão mais recente.
FROM ghcr.io/kafbat/kafka-ui:latest

# Expõe a porta 8080, que é a porta padrão da aplicação web.
# Isso serve como documentação e ajuda na configuração de redes.
EXPOSE 8080

# A imagem base já contém o comando (CMD) necessário para iniciar
# a aplicação, então você não precisa adicionar um aqui.
