FROM confluentinc/cp-kafka:7.6.1

# Use subdirectory específico para dados do Kafka dentro do volume
ENV KAFKA_LOG_DIRS=/var/lib/kafka/data/kafka-storage

# Não precisamos de scripts customizados, o Railway cuida das permissões
