[env]
KAFKA_BROKER_ID="1"
KAFKA_ZOOKEEPER_CONNECT="disciplined-mercy.railway.internal:2181"
KAFKA_LISTENERS="PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092,SASL_PLAINTEXT://0.0.0.0:9093"
KAFKA_ADVERTISED_LISTENERS="PLAINTEXT://zestful-joy.railway.internal:9092,PLAINTEXT_INTERNAL://zestful-joy.railway.internal:29092,SASL_PLAINTEXT://zestful-joy.railway.internal:9093"
KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT"
KAFKA_INTER_BROKER_LISTENER_NAME="PLAINTEXT_INTERNAL"
KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="1"
KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS="0"
KAFKA_AUTO_CREATE_TOPICS_ENABLE="true"


# Configurações de autenticação SASL/SCRAM apenas para clientes externos
KAFKA_SASL_ENABLED_MECHANISMS="SCRAM-SHA-256,SCRAM-SHA-512"
KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL="PLAINTEXT"

API_KEY="12345678"
API_SECRET="12345678"
